import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{ padding: "1rem", borderBottom: "1px solid #ccc" }}>
          <nav>
            <Link href="/">Home</Link> |{" "}
            <Link href="/posts/1">Post 1</Link> |{" "}
            <Link href="/dashboard">Dashboard</Link> |{" "}
            <Link href="/login">Login</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
